// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhgjdhzrmkmgvneuayji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloZ2pkaHpybWttZ3ZuZXVheWppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzYwOTUsImV4cCI6MjA2NjQ1MjA5NX0.CtqSXVQDZ-vwN83XyjHgAdWvctiX7S_JP8z9Capujk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);